global:
  domain: argocd.lab.noah-gallo.com

configs:
  cm:
    admin.enabled: "true"
    # Use annotation for resource tracking to avoid label conflicts
    application.resourceTrackingMethod: annotation
  params:
    server.insecure: "true"   # TLS terminated at Ingress level (Phase 6)

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

# Single-node control plane — no HA needed
redis-ha:
  enabled: false

controller:
  replicas: 1
