apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "2.4.0"
      helm:
        releaseName: external-secrets
        valueFiles:
          - $homelab/platform/external-secrets/values.yaml
    - repoURL: https://github.com/NoahGallo/homelab-gitops
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://github.com/NoahGallo/homelab-gitops
      targetRevision: HEAD
      path: platform/external-secrets/config
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
